---
title: "Po-Lin Wang"
#Let's add all the files to our git staging area
#git add -A #the -A flag tells it git you want everything

#Now we can commit
#git commit -m "My first website commit. The begining of greatness"

#Now we push. Note the addendum to normal pushing
#git push origin master
---
****************
>
| PhD Candidate
|
| Department of Insurance Legal Studies, and Real Estate
| B417 Amos Hall 
| Terry College of Business
| University of Georgia
| Athens, GA, 30602
|
| Email: [polinwang@uga.edu](mailto:polinwang@uga.edu)

\
\


#### Curriculum vitae

Download my [CV](https://drive.google.com/file/d/1UEHBgPeGOMO2MT3hlF-U8TjOobwGsdYn/view?usp=sharing)

#### Research Interests

Mortality modeling, asset liability management, generational wealth accounts, and market discipine


#### Society of Actuary (SOA) Exams Completed:

- P (Probability)
- FM (Financial Mathematics)
- MFE (Models for Financial Economics)
- MLC (Models for Life Contingencies)
- C (Construction and Evaluation of Actuarial Models)

#### Awards and Honors

- 2019 S.S. Huebner Doctoral Colloquium
- 2018 Harris Schlesinger Memorial Doctoral Research Award
- 2018 University of Georgia RMIN Summer Research Scholarship
- 2012 Taiwan Insurance Best Performance Award - Best Innovation Product (Co-designer)

#### Programming Languages

- VBA (professional with insurance pricing and reserving experience)
- Prophet (professional with insurance pricing and reserving experience)
- Matlab (asset liability optimization projects)
- R (recently developed interests in)

************

Last updated : `r format(Sys.time(), '%B, %Y')`